repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        stages: [commit]
        types: [python]
        entry: poetry run isort . --no-inline-sort
        language: system
        pass_filenames: false
        always_run: true
      - id: black
        name: black
        stages: [commit]
        types: [python]
        entry: poetry run black .
        language: system
        pass_filenames: false
        always_run: true
      - id: ruff
        name: ruff
        stages: [commit]
        types: [python]
        entry: poetry run ruff check .
        language: system
        pass_filenames: false
        always_run: true
        fail_fast: true
